### Load packages

In [1]:
import pandas as pd
import numpy as np

### Load the data

In [2]:
data1 = pd.read_csv(r'G:\My Drive\Skole\DTU\10. semester\02806 Social_data_viz\10_sem\Lectures\Data\2003_to_2018.csv')
data2 = pd.read_csv(r'G:\My Drive\Skole\DTU\10. semester\02806 Social_data_viz\10_sem\Lectures\Data\SF_Data_2018_to_Present.csv')

### Check the data

In [3]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2129525 entries, 0 to 2129524
Data columns (total 35 columns):
 #   Column                                                    Dtype
---  ------                                                    -----
 0   PdId                                                      int64
 1   IncidntNum                                                int64
 2   Incident Code                                             int64
 3   Category                                                  object
 4   Descript                                                  object
 5   DayOfWeek                                                 object
 6   Date                                                      object
 7   Time                                                      object
 8   PdDistrict                                                object
 9   Resolution                                                object
 10  Address                                                   object
 11  X                                                         float64
 12  Y                                                         float64
 13  location                                                  object
 14  SF Find Neighborhoods 2 2                                 float64
 15  Current Police Districts 2 2                              float64
 16  Current Supervisor Districts 2 2                          float64
 17  Analysis Neighborhoods 2 2                                float64
 18  DELETE - Fire Prevention Districts 2 2                    float64
 19  DELETE - Police Districts 2 2                             float64
 20  DELETE - Supervisor Districts 2 2                         float64
 21  DELETE - Zip Codes 2 2                                    float64
 22  DELETE - Neighborhoods 2 2                                float64
 23  DELETE - 2017 Fix It Zones 2 2                            float64
 24  Civic Center Harm Reduction Project Boundary 2 2          float64
 25  Fix It Zones as of 2017-11-06  2 2                        float64
 26  DELETE - HSOC Zones 2 2                                   float64
 27  Fix It Zones as of 2018-02-07 2 2                         float64
 28  CBD, BID and GBD Boundaries as of 2017 2 2                float64
 29  Areas of Vulnerability, 2016 2 2                          float64
 30  Central Market/Tenderloin Boundary 2 2                    float64
 31  Central Market/Tenderloin Boundary Polygon - Updated 2 2  float64
 32  HSOC Zones as of 2018-06-05 2 2                           float64
 33  OWED Public Spaces 2 2                                    float64
 34  Neighborhoods 2                                           float64
dtypes: float64(23), int64(3), object(9)
memory usage: 568.6+ MB

In [4]:
data1_keep = ['Category', 'Date', 'Time', 'DayOfWeek', 'Incident Code', 'Descript', 'PdDistrict', 'X', 'Y']

In [5]:
df1 = data1[data1_keep]

In [6]:
df1.head(2)

,Category,Date,Time,DayOfWeek,Incident Code,Descript,PdDistrict,X,Y
0,ROBBERY,11/22/2004,17:50,Monday,3074,"ROBBERY, BODILY FORCE",INGLESIDE,-122.420084,37.708311
1,VEHICLE THEFT,10/18/2005,20:00,Tuesday,7021,STOLEN AUTOMOBILE,PARK,-120.500000,90.000000

In [7]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003940 entries, 0 to 1003939
Data columns (total 29 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   Row ID                    1003940 non-null  int64
 1   Incident Datetime         1003940 non-null  object
 2   Incident Date             1003940 non-null  object
 3   Incident Time             1003940 non-null  object
 4   Incident Year             1003940 non-null  int64
 5   Incident Day of Week      1003940 non-null  object
 6   Report Datetime           1003940 non-null  object
 7   Incident ID               1003940 non-null  int64
 8   Incident Number           1003940 non-null  int64
 9   CAD Number                778183 non-null   float64
 10  Report Type Code          1003940 non-null  object
 11  Report Type Description   1003940 non-null  object
 12  Filed Online              197866 non-null   object
 13  Incident Code             1003940 non-null  int64
 14  Incident Category         1002432 non-null  object
 15  Incident Subcategory      1002432 non-null  object
 16  Incident Description      1003940 non-null  object
 17  Resolution                1003940 non-null  object
 18  Intersection              948540 non-null   object
 19  CNN                       948540 non-null   float64
 20  Police District           1003940 non-null  object
 21  Analysis Neighborhood     948243 non-null   object
 22  Supervisor District       947911 non-null   float64
 23  Supervisor District 2012  948448 non-null   float64
 24  Latitude                  948540 non-null   float64
 25  Longitude                 948540 non-null   float64
 26  Point                     948540 non-null   object
 27  data_as_of                1003940 non-null  object
 28  data_loaded_at            1003940 non-null  object
dtypes: float64(6), int64(5), object(18)
memory usage: 222.1+ MB

In [8]:
data2_keep = ['Incident Category', 'Incident Datetime','Incident Day of Week', 'Incident Code',
                   'Incident Description', 'Police District','Longitude', 'Latitude']

In [9]:
df2 = data2[data2_keep]

In [10]:
df2.head(2)

,Incident Category,Incident Datetime,Incident Day of Week,Incident Code,Incident Description,Police District,Longitude,Latitude
0,Recovered Vehicle,2025/08/26 11:17:00 PM,Tuesday,7041,"Vehicle, Recovered, Auto",Out of SF,NaN,NaN
1,Assault,2025/08/27 12:37:00 AM,Wednesday,4134,Battery,Park,-122.449013,37.780415

### Mapping between the datasets

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2129525 entries, 0 to 2129524
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   Category       object
 1   Date           object
 2   Time           object
 3   DayOfWeek      object
 4   Incident Code  int64
 5   Descript       object
 6   PdDistrict     object
 7   X              float64
 8   Y              float64
dtypes: float64(2), int64(1), object(6)
memory usage: 146.2+ MB

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003940 entries, 0 to 1003939
Data columns (total 8 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Incident Category     1002432 non-null  object
 1   Incident Datetime     1003940 non-null  object
 2   Incident Day of Week  1003940 non-null  object
 3   Incident Code         1003940 non-null  int64
 4   Incident Description  1003940 non-null  object
 5   Police District       1003940 non-null  object
 6   Longitude             948540 non-null   float64
 7   Latitude              948540 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 61.3+ MB

In [13]:
df1['Incident Datetime'] = pd.to_datetime(df1['Date'] + ' ' + df1['Time'], format='%m/%d/%Y %H:%M')

C:\Users\victo\AppData\Local\Temp\ipykernel_24456\1687535536.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Incident Datetime'] = pd.to_datetime(df1['Date'] + ' ' + df1['Time'], format='%m/%d/%Y %H:%M')

In [14]:
df1 = df1.drop(columns=['Date', 'Time'])

In [15]:
df2['Incident Datetime'] = pd.to_datetime(df2['Incident Datetime'], format='%Y/%m/%d %I:%M:%S %p')

C:\Users\victo\AppData\Local\Temp\ipykernel_24456\3910846489.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Incident Datetime'] = pd.to_datetime(df2['Incident Datetime'], format='%Y/%m/%d %I:%M:%S %p')

In [16]:
df1 = df1.rename(columns={'X': 'Longitude', 'Y': 'Latitude', 'Category': 'Incident Category', 'DayOfWeek': 'Incident Day of Week', 'Descript': 'Incident Description', 'PdDistrict': 'Police District'})

In [17]:
reorder = ['Incident Category', 'Incident Datetime', 'Incident Day of Week', 'Incident Code', 'Incident Description', 'Police District', 'Longitude', 'Latitude']
df1 = df1[reorder]

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2129525 entries, 0 to 2129524
Data columns (total 8 columns):
 #   Column                Dtype
---  ------                -----
 0   Incident Category     object
 1   Incident Datetime     datetime64[ns]
 2   Incident Day of Week  object
 3   Incident Code         int64
 4   Incident Description  object
 5   Police District       object
 6   Longitude             float64
 7   Latitude              float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 130.0+ MB

In [19]:
print(df1.head(2))

  Incident Category   Incident Datetime Incident Day of Week  Incident Code  \
0           ROBBERY 2004-11-22 17:50:00               Monday           3074
1     VEHICLE THEFT 2005-10-18 20:00:00              Tuesday           7021

    Incident Description Police District   Longitude   Latitude
0  ROBBERY, BODILY FORCE       INGLESIDE -122.420084  37.708311
1      STOLEN AUTOMOBILE            PARK -120.500000  90.000000

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003940 entries, 0 to 1003939
Data columns (total 8 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Incident Category     1002432 non-null  object
 1   Incident Datetime     1003940 non-null  datetime64[ns]
 2   Incident Day of Week  1003940 non-null  object
 3   Incident Code         1003940 non-null  int64
 4   Incident Description  1003940 non-null  object
 5   Police District       1003940 non-null  object
 6   Longitude             948540 non-null   float64
 7   Latitude              948540 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 61.3+ MB

### Now we need to check that they name the categories in the same way

In [21]:
print(df1['Incident Category'].unique())
print(df2['Incident Category'].unique())

['ROBBERY' 'VEHICLE THEFT' 'ARSON' 'ASSAULT' 'TRESPASS' 'BURGLARY'
 'LARCENY/THEFT' 'WARRANTS' 'OTHER OFFENSES' 'DRUG/NARCOTIC'
 'SUSPICIOUS OCC' 'LIQUOR LAWS' 'VANDALISM' 'WEAPON LAWS' 'NON-CRIMINAL'
 'MISSING PERSON' 'FRAUD' 'SEX OFFENSES, FORCIBLE' 'SECONDARY CODES'
 'DISORDERLY CONDUCT' 'RECOVERED VEHICLE' 'KIDNAPPING'
 'FORGERY/COUNTERFEITING' 'PROSTITUTION' 'DRUNKENNESS' 'BAD CHECKS'
 'DRIVING UNDER THE INFLUENCE' 'LOITERING' 'STOLEN PROPERTY' 'SUICIDE'
 'BRIBERY' 'EXTORTION' 'EMBEZZLEMENT' 'GAMBLING' 'PORNOGRAPHY/OBSCENE MAT'
 'SEX OFFENSES, NON FORCIBLE' 'TREA']
['Recovered Vehicle' 'Assault' 'Fraud' 'Larceny Theft'
 'Motor Vehicle Theft' 'Suspicious Occ' 'Warrant' 'Disorderly Conduct'
 'Miscellaneous Investigation' 'Malicious Mischief' 'Other Miscellaneous'
 'Non-Criminal' 'Stolen Property' nan 'Drug Offense' 'Robbery'
 'Weapons Offense' 'Arson' 'Missing Person' 'Lost Property' 'Burglary'
 'Courtesy Report' 'Traffic Violation Arrest' 'Forgery And Counterfeiting'
 'Weapons Carrying Etc' 'Other Offenses'
 'Offences Against The Family And Children' 'Other' 'Traffic Collision'
 'Case Closure' 'Vehicle Impounded' 'Suicide' 'Drug Violation' 'Vandalism'
 'Gambling' 'Homicide' 'Fire Report' 'Rape' 'Civil Sidewalks'
 'Prostitution' 'Human Trafficking, Commercial Sex Acts'
 'Vehicle Misplaced' 'Embezzlement' 'Suspicious' 'Sex Offense'
 'Liquor Laws' 'Weapons Offence' 'Motor Vehicle Theft?'
 'Human Trafficking (A), Commercial Sex Acts'
 'Human Trafficking (B), Involuntary Servitude']

In [22]:
category_mappings = {
    'ROBBERY': 'Robbery',
    'VEHICLE THEFT': 'Motor Vehicle Theft',
    'ARSON': 'Arson',
    'ASSAULT': 'Assault',
    'TRESPASS': 'Miscellaneous Investigation',
    'BURGLARY': 'Burglary',
    'LARCENY/THEFT': 'Larceny Theft',
    'WARRANTS': 'Warrant',
    'OTHER OFFENSES': 'Other Offenses',
    'DRUG/NARCOTIC': 'Drug Offense',
    'SUSPICIOUS OCC': 'Suspicious Occ',
    'LIQUOR LAWS': 'Liquor Laws',
    'VANDALISM': 'Vandalism',
    'WEAPON LAWS': 'Weapons Offense',
    'NON-CRIMINAL': 'Non-Criminal',
    'MISSING PERSON': 'Missing Person',
    'FRAUD': 'Fraud',
    'SEX OFFENSES, FORCIBLE': 'Rape',
    'SECONDARY CODES': 'Other Miscellaneous',
    'DISORDERLY CONDUCT': 'Disorderly Conduct',
    'RECOVERED VEHICLE': 'Recovered Vehicle',
    'KIDNAPPING': 'Offences Against The Family And Children',
    'FORGERY/COUNTERFEITING': 'Forgery And Counterfeiting',
    'PROSTITUTION': 'Prostitution',
    'DRUNKENNESS': 'Liquor Laws',
    'BAD CHECKS': 'Fraud',
    'DRIVING UNDER THE INFLUENCE': 'Traffic Violation Arrest',
    'LOITERING': 'Disorderly Conduct',
    'STOLEN PROPERTY': 'Stolen Property',
    'SUICIDE': 'Suicide',
    'BRIBERY': 'Other Miscellaneous',
    'EXTORTION': 'Other Miscellaneous',
    'EMBEZZLEMENT': 'Embezzlement',
    'GAMBLING': 'Gambling',
    'PORNOGRAPHY/OBSCENE MAT': 'Sex Offense',
    'SEX OFFENSES, NON FORCIBLE': 'Sex Offense',
    'TREA': 'Miscellaneous Investigation'
}

In [23]:
df1['Incident Category'] = df1['Incident Category'].replace(category_mappings)

In [24]:
print(df1['Incident Category'].unique())
print(df2['Incident Category'].unique())

['Robbery' 'Motor Vehicle Theft' 'Arson' 'Assault'
 'Miscellaneous Investigation' 'Burglary' 'Larceny Theft' 'Warrant'
 'Other Offenses' 'Drug Offense' 'Suspicious Occ' 'Liquor Laws'
 'Vandalism' 'Weapons Offense' 'Non-Criminal' 'Missing Person' 'Fraud'
 'Rape' 'Other Miscellaneous' 'Disorderly Conduct' 'Recovered Vehicle'
 'Offences Against The Family And Children' 'Forgery And Counterfeiting'
 'Prostitution' 'Traffic Violation Arrest' 'Stolen Property' 'Suicide'
 'Embezzlement' 'Gambling' 'Sex Offense']
['Recovered Vehicle' 'Assault' 'Fraud' 'Larceny Theft'
 'Motor Vehicle Theft' 'Suspicious Occ' 'Warrant' 'Disorderly Conduct'
 'Miscellaneous Investigation' 'Malicious Mischief' 'Other Miscellaneous'
 'Non-Criminal' 'Stolen Property' nan 'Drug Offense' 'Robbery'
 'Weapons Offense' 'Arson' 'Missing Person' 'Lost Property' 'Burglary'
 'Courtesy Report' 'Traffic Violation Arrest' 'Forgery And Counterfeiting'
 'Weapons Carrying Etc' 'Other Offenses'
 'Offences Against The Family And Children' 'Other' 'Traffic Collision'
 'Case Closure' 'Vehicle Impounded' 'Suicide' 'Drug Violation' 'Vandalism'
 'Gambling' 'Homicide' 'Fire Report' 'Rape' 'Civil Sidewalks'
 'Prostitution' 'Human Trafficking, Commercial Sex Acts'
 'Vehicle Misplaced' 'Embezzlement' 'Suspicious' 'Sex Offense'
 'Liquor Laws' 'Weapons Offence' 'Motor Vehicle Theft?'
 'Human Trafficking (A), Commercial Sex Acts'
 'Human Trafficking (B), Involuntary Servitude']

### Checking for others misalignments

In [25]:
print(df1['Police District'].unique())
print(df2['Police District'].unique())

['INGLESIDE' 'PARK' 'SOUTHERN' 'TARAVAL' 'TENDERLOIN' 'BAYVIEW' 'CENTRAL'
 'NORTHERN' 'MISSION' 'RICHMOND' nan]
['Out of SF' 'Park' 'Northern' 'Bayview' 'Central' 'Ingleside' 'Taraval'
 'Richmond' 'Mission' 'Tenderloin' 'Southern']

In [26]:
district_mappings = {
    'INGLESIDE': 'Ingleside',
    'PARK': 'Park',
    'SOUTHERN': 'Southern',
    'TARAVAL': 'Taraval',
    'TENDERLOIN': 'Tenderloin',
    'BAYVIEW': 'Bayview',
    'CENTRAL': 'Central',
    'NORTHERN': 'Northern',
    'MISSION': 'Mission',
    'RICHMOND': 'Richmond',
    float('nan'): 'Out of SF'
}

In [27]:
df1['Police District'] = df1['Police District'].replace(district_mappings)

In [28]:
print(df1['Police District'].unique())
print(df2['Police District'].unique())

['Ingleside' 'Park' 'Southern' 'Taraval' 'Tenderloin' 'Bayview' 'Central'
 'Northern' 'Mission' 'Richmond' 'Out of SF']
['Out of SF' 'Park' 'Northern' 'Bayview' 'Central' 'Ingleside' 'Taraval'
 'Richmond' 'Mission' 'Tenderloin' 'Southern']

## Great. Now we can merge into one dataframe

In [29]:
merged_data = pd.concat([df1, df2], axis=0, ignore_index=True) # Perform concat

In [30]:
merged_data.head()

,Incident Category,Incident Datetime,Incident Day of Week,Incident Code,Incident Description,Police District,Longitude,Latitude
0,Robbery,2004-11-22 17:50:00,Monday,3074,"ROBBERY, BODILY FORCE",Ingleside,-122.420084,37.708311
1,Motor Vehicle Theft,2005-10-18 20:00:00,Tuesday,7021,STOLEN AUTOMOBILE,Park,-120.500000,90.000000
2,Motor Vehicle Theft,2004-02-15 02:00:00,Sunday,7021,STOLEN AUTOMOBILE,Southern,-120.500000,90.000000
3,Arson,2011-02-18 05:27:00,Friday,26030,ARSON,Ingleside,-122.436220,37.724377
4,Assault,2010-11-21 17:00:00,Sunday,4134,BATTERY,Southern,-122.410541,37.770913

In [31]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3133465 entries, 0 to 3133464
Data columns (total 8 columns):
 #   Column                Dtype
---  ------                -----
 0   Incident Category     object
 1   Incident Datetime     datetime64[ns]
 2   Incident Day of Week  object
 3   Incident Code         int64
 4   Incident Description  object
 5   Police District       object
 6   Longitude             float64
 7   Latitude              float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 191.3+ MB

### Let us again merge similar categories

In [32]:
merged_data['Incident Category'].unique()

array(['Robbery', 'Motor Vehicle Theft', 'Arson', 'Assault',
       'Miscellaneous Investigation', 'Burglary', 'Larceny Theft',
       'Warrant', 'Other Offenses', 'Drug Offense', 'Suspicious Occ',
       'Liquor Laws', 'Vandalism', 'Weapons Offense', 'Non-Criminal',
       'Missing Person', 'Fraud', 'Rape', 'Other Miscellaneous',
       'Disorderly Conduct', 'Recovered Vehicle',
       'Offences Against The Family And Children',
       'Forgery And Counterfeiting', 'Prostitution',
       'Traffic Violation Arrest', 'Stolen Property', 'Suicide',
       'Embezzlement', 'Gambling', 'Sex Offense', 'Malicious Mischief',
       nan, 'Lost Property', 'Courtesy Report', 'Weapons Carrying Etc',
       'Other', 'Traffic Collision', 'Case Closure', 'Vehicle Impounded',
       'Drug Violation', 'Homicide', 'Fire Report', 'Civil Sidewalks',
       'Human Trafficking, Commercial Sex Acts', 'Vehicle Misplaced',
       'Suspicious', 'Weapons Offence', 'Motor Vehicle Theft?',
       'Human Trafficking (A), Commercial Sex Acts',
       'Human Trafficking (B), Involuntary Servitude'], dtype=object)

In [33]:
category_fine_tuning = {
    # Spelling & Punctuation cleanup
    'Motor Vehicle Theft?': 'Motor Vehicle Theft',
    'Weapons Offence': 'Weapons Offense',
    'Weapons Carrying Etc': 'Weapons Offense',
    
    # User-specified Human Trafficking mapping
    'Human Trafficking (A), Commercial Sex Acts': 'Prostitution',
    'Human Trafficking, Commercial Sex Acts': 'Prostitution',
    'Human Trafficking (B), Involuntary Servitude': 'Rape',
    
    # Naming convention overlap
    'Drug Violation': 'Drug Offense',
    'Suspicious': 'Suspicious Occ',
    'Malicious Mischief': 'Vandalism',
    
    # Miscellaneous consolidation
    'Other Miscellaneous': 'Other Offenses',
    'Other': 'Other Offenses'
}

In [34]:
merged_data['Incident Category'] = merged_data['Incident Category'].replace(category_fine_tuning)

In [35]:
print(merged_data['Incident Datetime'].dt.year.unique())

[2004 2005 2011 2010 2013 2017 2016 2006 2009 2012 2003 2007 2008 2015
 2014 2018 2025 2024 2020 2019 2022 2023 2021 2026]

### Only include full years

In [36]:
# 1. Get the absolute latest timestamp in the data
latest_timestamp = merged_data['Incident Datetime'].max()

# 2. Define what the "end of that year" would be
# This creates a timestamp for Dec 31st of that year
end_of_year = pd.Timestamp(year=latest_timestamp.year, month=12, day=31)

# 3. Logic: If the latest data point is BEFORE the end of its year, 
# it's an incomplete year.
if latest_timestamp < end_of_year:
    df_filtered = merged_data[merged_data['Incident Datetime'].dt.year < latest_timestamp.year]
else:
    # If the data goes all the way to Dec 31st, keep everything
    df_filtered = merged_data.copy()

In [37]:
df_filtered['Incident Datetime'].dt.year.unique()

array([2004, 2005, 2011, 2010, 2013, 2017, 2016, 2006, 2009, 2012, 2003,
       2007, 2008, 2015, 2014, 2018, 2025, 2024, 2020, 2019, 2022, 2023,
       2021])

In [38]:
print("Row counts per year:")
print(df_filtered['Incident Datetime'].dt.year.value_counts().sort_index())

Row counts per year:
Incident Datetime
2003    142803
2004    142054
2005    137048
2006    131856
2007    131771
2008    135242
2009    134309
2010    127758
2011    126713
2012    135464
2013    147664
2014    144844
2015    151459
2016    145994
2017    149487
2018    192565
2019    143027
2020    114601
2021    125336
2022    133048
2023    130932
2024    109116
2025     93749
Name: count, dtype: int64

In [39]:
print(df_filtered['Police District'].unique())

['Ingleside' 'Park' 'Southern' 'Taraval' 'Tenderloin' 'Bayview' 'Central'
 'Northern' 'Mission' 'Richmond' 'Out of SF']

In [40]:
# Save the merged DataFrame to a CSV file
df_filtered.to_csv("merged_data.csv", index=False)